/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UsersIndexRouteImport } from './routes/users/index'
import { Route as SettingsIndexRouteImport } from './routes/settings/index'
import { Route as ReservationsIndexRouteImport } from './routes/reservations/index'
import { Route as OverheadCameraIndexRouteImport } from './routes/overhead-camera/index'
import { Route as MapIndexRouteImport } from './routes/map/index'
import { Route as LotsIndexRouteImport } from './routes/lots/index'
import { Route as LoginIndexRouteImport } from './routes/login/index'
import { Route as GateCameraIndexRouteImport } from './routes/gate-camera/index'
import { Route as ExampleIndexRouteImport } from './routes/example/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as LotsRegisterIndexRouteImport } from './routes/lots/register/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersIndexRoute = UsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReservationsIndexRoute = ReservationsIndexRouteImport.update({
  id: '/reservations/',
  path: '/reservations/',
  getParentRoute: () => rootRouteImport,
} as any)
const OverheadCameraIndexRoute = OverheadCameraIndexRouteImport.update({
  id: '/overhead-camera/',
  path: '/overhead-camera/',
  getParentRoute: () => rootRouteImport,
} as any)
const MapIndexRoute = MapIndexRouteImport.update({
  id: '/map/',
  path: '/map/',
  getParentRoute: () => rootRouteImport,
} as any)
const LotsIndexRoute = LotsIndexRouteImport.update({
  id: '/lots/',
  path: '/lots/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginIndexRoute = LoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => rootRouteImport,
} as any)
const GateCameraIndexRoute = GateCameraIndexRouteImport.update({
  id: '/gate-camera/',
  path: '/gate-camera/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExampleIndexRoute = ExampleIndexRouteImport.update({
  id: '/example/',
  path: '/example/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => rootRouteImport,
} as any)
const LotsRegisterIndexRoute = LotsRegisterIndexRouteImport.update({
  id: '/lots/register/',
  path: '/lots/register/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/example/': typeof ExampleIndexRoute
  '/gate-camera/': typeof GateCameraIndexRoute
  '/login/': typeof LoginIndexRoute
  '/lots/': typeof LotsIndexRoute
  '/map/': typeof MapIndexRoute
  '/overhead-camera/': typeof OverheadCameraIndexRoute
  '/reservations/': typeof ReservationsIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/users/': typeof UsersIndexRoute
  '/lots/register/': typeof LotsRegisterIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/example': typeof ExampleIndexRoute
  '/gate-camera': typeof GateCameraIndexRoute
  '/login': typeof LoginIndexRoute
  '/lots': typeof LotsIndexRoute
  '/map': typeof MapIndexRoute
  '/overhead-camera': typeof OverheadCameraIndexRoute
  '/reservations': typeof ReservationsIndexRoute
  '/settings': typeof SettingsIndexRoute
  '/users': typeof UsersIndexRoute
  '/lots/register': typeof LotsRegisterIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/example/': typeof ExampleIndexRoute
  '/gate-camera/': typeof GateCameraIndexRoute
  '/login/': typeof LoginIndexRoute
  '/lots/': typeof LotsIndexRoute
  '/map/': typeof MapIndexRoute
  '/overhead-camera/': typeof OverheadCameraIndexRoute
  '/reservations/': typeof ReservationsIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/users/': typeof UsersIndexRoute
  '/lots/register/': typeof LotsRegisterIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard/'
    | '/example/'
    | '/gate-camera/'
    | '/login/'
    | '/lots/'
    | '/map/'
    | '/overhead-camera/'
    | '/reservations/'
    | '/settings/'
    | '/users/'
    | '/lots/register/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/example'
    | '/gate-camera'
    | '/login'
    | '/lots'
    | '/map'
    | '/overhead-camera'
    | '/reservations'
    | '/settings'
    | '/users'
    | '/lots/register'
  id:
    | '__root__'
    | '/'
    | '/dashboard/'
    | '/example/'
    | '/gate-camera/'
    | '/login/'
    | '/lots/'
    | '/map/'
    | '/overhead-camera/'
    | '/reservations/'
    | '/settings/'
    | '/users/'
    | '/lots/register/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  ExampleIndexRoute: typeof ExampleIndexRoute
  GateCameraIndexRoute: typeof GateCameraIndexRoute
  LoginIndexRoute: typeof LoginIndexRoute
  LotsIndexRoute: typeof LotsIndexRoute
  MapIndexRoute: typeof MapIndexRoute
  OverheadCameraIndexRoute: typeof OverheadCameraIndexRoute
  ReservationsIndexRoute: typeof ReservationsIndexRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
  UsersIndexRoute: typeof UsersIndexRoute
  LotsRegisterIndexRoute: typeof LotsRegisterIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users/': {
      id: '/users/'
      path: '/users'
      fullPath: '/users/'
      preLoaderRoute: typeof UsersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reservations/': {
      id: '/reservations/'
      path: '/reservations'
      fullPath: '/reservations/'
      preLoaderRoute: typeof ReservationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/overhead-camera/': {
      id: '/overhead-camera/'
      path: '/overhead-camera'
      fullPath: '/overhead-camera/'
      preLoaderRoute: typeof OverheadCameraIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/map/': {
      id: '/map/'
      path: '/map'
      fullPath: '/map/'
      preLoaderRoute: typeof MapIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lots/': {
      id: '/lots/'
      path: '/lots'
      fullPath: '/lots/'
      preLoaderRoute: typeof LotsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/': {
      id: '/login/'
      path: '/login'
      fullPath: '/login/'
      preLoaderRoute: typeof LoginIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gate-camera/': {
      id: '/gate-camera/'
      path: '/gate-camera'
      fullPath: '/gate-camera/'
      preLoaderRoute: typeof GateCameraIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/example/': {
      id: '/example/'
      path: '/example'
      fullPath: '/example/'
      preLoaderRoute: typeof ExampleIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lots/register/': {
      id: '/lots/register/'
      path: '/lots/register'
      fullPath: '/lots/register/'
      preLoaderRoute: typeof LotsRegisterIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  ExampleIndexRoute: ExampleIndexRoute,
  GateCameraIndexRoute: GateCameraIndexRoute,
  LoginIndexRoute: LoginIndexRoute,
  LotsIndexRoute: LotsIndexRoute,
  MapIndexRoute: MapIndexRoute,
  OverheadCameraIndexRoute: OverheadCameraIndexRoute,
  ReservationsIndexRoute: ReservationsIndexRoute,
  SettingsIndexRoute: SettingsIndexRoute,
  UsersIndexRoute: UsersIndexRoute,
  LotsRegisterIndexRoute: LotsRegisterIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
